### ISSUE TITLE
Number Balls aren't Affected by Gravity

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#14]
### Contact Details

@lishaduck

### What happened?

The number balls feel really unnatural and unsettling.

### Reproduction steps

1. Run the game.
2. Hit <kbd>1</kbd> a few times.
3. See the number ball not curve at all.

### What should have happened?

Number balls should slightly arc. Not much, becuase they're pure magic, but at least a bit.

### Date

2024-02-01

### What device are you seeing the problem on?

Macbook Air 2020 (M1)

### OS

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_**CC:** @MattsAttack_

**Comment by MattsAttack** [comment]
This shouldn't be horrible to fix. It's just a matter of making gravity a small factor. Idk if it needs it though

**Comment by lishaduck** [comment]
> This shouldn't be horrible to fix. It's just a matter of making gravity a small factor. Idk if it needs it though

We just need it to be really minor. Otherwise it looks weird, but it shouldn't be enough that the players need to think about it.

**Comment by iiAzui** [comment]
I dont know if we should add gravity to the balls i dont think it will feel good

**Comment by lishaduck** [comment]
> I dont know if we should add gravity to the balls i dont think it will feel good

Fair enough. I suppose the complexity outweighs the benefits, and we can just excuse it as "magic."

**Comment by iiAzui** [comment]
because it is magic

**Comment by lishaduck** [comment]
> because it is magic

Yup.
