### ISSUE TITLE
Number Balls aren't Affected by Walls

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#17]
### Contact Details

@lishaduck

### What happened?

The number balls feel  even more unnatural.

### Reproduction steps

1. Run the game.
2. Hit 1 a few times, aiming at a wall.
3. Watch the ball quantum tunnel.

### What should have happened?

Number balls should be affected by the walls.

### Date

2024-02-01

### What device are you seeing the problem on?

Macbook Air 2020 (M1)

### OS

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_**CC:** @MattsAttack_

**Comment by MattsAttack** [comment]
Fixed. Just made the tile map interact with layer 2
