### ISSUE TITLE
Info Labels don't Align Correctly

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#30]
### Contact Details

@lishaduck

### What happened?

The info labels don't align correctly in fullscreen (in #28).

### Reproduction steps

1. Start the game.
2. Go into fullscreen
3. Notice that info labels are just floating

### What should have happened?

They should stick to the top.

### Date

2024-02-03

### What device are you seeing the problem on?

Macbook Air 2020 (M1)

### OS

macOS

### Browser

Chrome

### Context

<img width="1491" alt="Screenshot 2024-02-03 at 4 37 59 PM" src="https://github.com/PHS-TSA/wizards-in-calculus/assets/88557639/71c6478a-fd2d-4f35-ab5c-311d2f62ed46">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_**CC:** @iiAzui_

**Comment by MattsAttack** [comment]
I think I know how to fix this. I’ll work on it when I get home.

**Comment by lishaduck** [comment]
> I think I know how to fix this. I’ll work on it when I get home.

Sounds good!

**Comment by iiAzui** [comment]
Looks like your playing in a old version, the window size is never ment to go past 1280 x 800, also why are you in chrome

**Comment by lishaduck** [comment]
> Looks like your playing in a old version, the window size is never ment to go past 1280 x 800, also why are you in chrome

No, it's the latest. I guess the web build doesn't enforce the screen size, so we'll still need to fix it as it has to be a web game. As for chrome: why not? I was testing the web build.

**Comment by lishaduck** [comment]
> >... the window size is never ment to go past 1280 x 800...
> 
> ...I guess the web build doesn't enforce the screen size, so we'll still need to fix it as it has to be a web game...

Tested it some more. That setting changes the default size but doesn't lock it on desktop.
It _is_ [this line](https://github.com/PHS-TSA/wizards-in-calculus/pull/28#discussion_r1477127611) doing it, right?

**Comment by iiAzui** [comment]
Idk it was in project settings
I also made it so it can't be risized

**Comment by lishaduck** [comment]
> Idk it was in project settings I also made it so it can't be risized

Ah. Must have accidentally reverted that. I do think we _should_ fix it eventually, I think fixing that should be enough for now.

**Comment by lishaduck** [comment]
> > Idk it was in project settings I also made it so it can't be risized
> 
> Ah. Must have accidentally reverted that. I do think we _should_ fix it eventually, I think fixing that should be enough for now.

I see. That checkmark is weird. I'll push it after testing it in the browser.

**Comment by lishaduck** [comment]
> > > Idk it was in project settings I also made it so it can't be risized
> > 
> > 
> > Ah. Must have accidentally reverted that. I do think we _should_ fix it eventually, I think fixing that should be enough for now.
> 
> I see. That checkmark is weird. I'll push it after testing it in the browser.

Yeah. It isn't enforced in the browser, so that fix doesn't do ~~anything~~much. @MattsAttack, you can give it a shot.

**Comment by lishaduck** [comment]
This is only mostly related, but I found another bug with the info labels:
<img width="317" alt="Screenshot 2024-02-04 at 9 06 32 PM" src="https://github.com/PHS-TSA/wizards-in-calculus/assets/88557639/09f7f588-f9c6-4d8c-82b7-118ec5101928">

The z-index of the bg is behind the rest of the content, which'll also need to get fixed.

**Comment by iiAzui** [comment]
That's not lable that's the button

**Comment by MattsAttack** [comment]
does it need to be a button or can i change it to a color rect?

**Comment by iiAzui** [comment]
You can change it, I was just going crazy that day and couldn't find it, I
just want a background

**Comment by MattsAttack** [comment]
i gotchu

**Comment by MattsAttack** [comment]
We should probably edit the camera to just fit whatever resolution normal chrome uses. That way when the judges play it they can do full screen and it looks pretty

**Comment by lishaduck** [comment]
> We should probably edit the camera to just fit whatever resolution normal chrome uses. That way when the judges play it they can do full screen and it looks pretty

I was thinking we shouldn't care about the resolution and place them dynamically. Then they could do it fullscreen, but they don't have to.

**Comment by lishaduck** [comment]
Aha! We can [anchor](https://docs.godotengine.org/en/stable/tutorials/ui/size_and_anchors.html) them.

**Comment by lishaduck** [comment]
I'm going to try to tackle this one next.

**Comment by lishaduck** [comment]
I got it working! I just have to hook the score back up and it'll be done.

**Comment by lishaduck** [comment]
Fixed it! Also found some bugs left over from #42, so it really ought to get merged whether or not you like the approach, for it can be changed later.
