### ISSUE TITLE
Fix Grass in TileSet

### ISSUE THREAD

**Issue by MattsAttack** [PHS-TSA/wizards-in-calculus#34]
### Why

The way the grass cuts off on corners looks really tacky. We should make a updated tile map that has corner blocks where the grass goes around
![image](https://github.com/PHS-TSA/wizards-in-calculus/assets/71449347/b7dbf78a-529d-4b1a-ba98-c2d714e4f1e6)
Kind of like how minecraft does them
![image](https://github.com/PHS-TSA/wizards-in-calculus/assets/71449347/6e76cfa5-6d0c-441c-ae8f-d80a731449ad)

### The Plan

Create updated tile map
Fix affected areas

**Comment by iiAzui** [comment]
We shouldn't have grass on walls
But a block where the grass goes down a little bit might look good
Also upsidedown slopes
And blocks that have the corner grass because slopes look bad
Maybe something else to go on the walls?

**Comment by MattsAttack** [comment]
my bad by walls i meant like the boarders. The parts i circled here
![302168608-b7dbf78a-529d-4b1a-ba98-c2d714e4f1e6](https://github.com/PHS-TSA/wizards-in-calculus/assets/71449347/ed589bff-cb71-4b97-b781-b94399598270)

**Comment by iiAzui** [comment]
Yeah, we shouldn't have grass on the walls lol, like how it's placed there,
that should just be dirt I think idk how it would look if it was all grass

**Comment by MattsAttack** [comment]
Ya that minecraft photo was a bad example. More like this
![image](https://github.com/PHS-TSA/wizards-in-calculus/assets/71449347/30dd671e-8c35-4bc7-af69-28103bd450cb)

**Comment by iiAzui** [comment]
I just don't know if it will look super good, I understand what you mean we
can try it but I liked just dirt walls instead of grass walls like you have
currently

**Comment by lishaduck** [comment]
I see what you mean, but I like the grass 😉. Either way, we definitely need a block for under slopes.

**Comment by lishaduck** [comment]
I believe this has now been fixed w/ thanks to @iiAzui for fixing the tilemap and @MattsAttack for retiling the levels in #76!

**Comment by lishaduck** [comment]
I believe this has now been fixed w/thanks to @iiAzui for fixing the tilemap and @MattsAttack for retiling the levels in #76!
