### ISSUE TITLE
Tutorial Change

### ISSUE THREAD

**Issue by MattsAttack** [PHS-TSA/wizards-in-calculus#35]
### Why

When we finalize the game we should probably have you start under the "welcome to...". Right now it looks kind of tacky. If the judges got confused it could lose us a lot points.
![image](https://github.com/PHS-TSA/wizards-in-calculus/assets/71449347/e5fa35ff-39bc-4e1c-bedf-6831241f3ff0)
I think having a way to skip the tutorial is still cool though so we could have some wall thats hard to wall jump up to the left with a teleporter to the first level (Like the easter egg Rhys put on the first level on Friday)

### The Plan

Change tutorial to be more linear

**Comment by MattsAttack** [comment]
Just realized there is a similar thing in this version lol. My bad. Still though we should probably make it more obvious

**Comment by lishaduck** [comment]
> we should probably make it more obvious

@iiAzui disagrees.
